development:
  HOST: <DEVELOPMENT_SERVICE_HOSTNAME>
  PORT: <DEVELOPMENT_SERVICE_PORT>
  ORIGIN: <DEVELOPMENT_CORS_ORIGIN>

# development:
#   HOST: 127.0.0.1
#   PORT: 3000
#   ORIGIN: '*'
#
# OR
#
#   ORIGIN:
#     - https://127.0.0.1:3000
#     - https://0.0.0.0:3000

production:
  HOST: <PRODUCTION_SERVICE_HOSTNAME>
  PORT: <PRODUCTION_SERVICE_PORT>
  ORIGIN:
    - <PRODUCTION_CORS_ORIGIN_1>
    - <PRODUCTION_CORS_ORIGIN_2>
