development:
  HOST: <DEVELOPMENT_SERVICE_HOSTNAME>
  ORIGIN: <DEVELOPMENT_CORS_ORIGIN>
  PORT: <DEVELOPMENT_SERVICE_PORT>
  SWAGGER_ENABLED: true

# development:
#   HOST: 127.0.0.1
#   PORT: 3000
#   ORIGIN: '*'
#
# OR
#
#   ORIGIN:
#     - https://127.0.0.1:3000
#     - https://0.0.0.0:3000

production:
  HOST: <PRODUCTION_SERVICE_HOSTNAME>
  ORIGIN:
    - <PRODUCTION_CORS_ORIGIN_1>
    - <PRODUCTION_CORS_ORIGIN_2>
 PORT: <PRODUCTION_SERVICE_PORT>
 SWAGGER_ENABLED: false

# Required for Cypress CORS integration tests (npm run test:cors:valid / test:cors:invalid)
cors-valid:
  HOST: 127.0.0.1
  ORIGIN:
    - http://localhost:3100
  PORT: 3000
  SWAGGER_ENABLED: false

cors-invalid:
  HOST: 127.0.0.1
  ORIGIN:
    - https://example.com
  PORT: 3000
  SWAGGER_ENABLED: false
